nama: Mulai vps 2.0 Anda

aktif: alur kerja_pengiriman

Pekerjaan:
  membangun:

    berjalan pada: windows-terbaru
    batas waktu-menit: 99999

    tangga:
    - nama: Unduh Ngrok
      jalankan: |
        Panggil-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stabil-windows-amd64.zip -OutFile ngrok.zip
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/start.bat -OutFile start.bat
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/wallpaper.png -OutFile wallpaper.png
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/wallpaper.bat -OutFile wallpaper.bat
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/loop.bat -OutFile loop.bat
    - nama: Unduh Peluncur
      jalankan: |
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Panggil-WebRequest https://raw.githubusercontent.com/mrajapati/DuckVPS/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - nama: Mengekstrak File Ngrok
      jalankan: Perluas-Arsipkan ngrok.zip
    - nama: Hubungkan ke Akun Ngrok
      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      lingkungan:
        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}
    - nama: Aktifkan Akses RDP
      jalankan: |
        Set-ItemProperty -Jalur 'HKLM:\Sistem\CurrentControlSet\Kontrol\Terminal Server' -nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Jalur 'HKLM:\Sistem\CurrentControlSet\Kontrol\Terminal Server\WinStations\RDP-Tcp' -nama "AutentikasiPengguna" -Nilai 1
        salin wallpaper.png D:\a\wallpaper.png
        salin wallpaper.bat D:\a\wallpaper.bat
        salin Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        salin "Visual Studio 2019.lnk" "C:\Pengguna\Publik\Desktop\Visual Studio 2019.lnk"
    - nama: Buat Terowongan
      jalankan: Mulai-Proses Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - nama: Hubungkan ke RDP Anda
      jalankan: cmd /c start.bat
    - nama: Berhasil! Anda Dapat Menutup Tab Sekarang
      jalankan: cmd /c loop.bat
